### ISSUE TITLE
just want your help

### ISSUE THREAD

**Issue by nguyentrithong** [enigma522/Spider#1]
hello, i'm very sorry to bother you, i see you are the author of a challenge named disk on securinets 2024. since there is no way to contact you so i have to do this, i want to discuss with you about the answers of the challenge i tried very hard but still can't find the flag, hope you can help me, i'm just a student, because i don't know your social media account so please take the initiative to contact me via discord: tri_thong, thank you very much

**Comment by enigma522** [comment]
you can contact me on discord enigma1336
